<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>meniu</name>
   <tag></tag>
   <elementGuidId>67bb07a7-4981-4574-a8df-31315cd05930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='sidebar-menu']/li[4]/div/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='sidebar-menu']/li[4]/div/i[2]</value>
   </webElementProperties>
</WebElementEntity>
